services:
  discord-bot:
    build: .
    container_name: discord-bot
    restart: always
    environment:
      - APP_TYPE=bot
      - DATABASE_URL=postgresql+psycopg2://gc-xdefiant:3a56ba95118f2dda2de6da3d2da18e1a@database:5432/gc-xdefiant
    volumes:
      - data-xdefiant:/app
    depends_on:
      - database

  scheduler:
    build: .
    container_name: scheduler
    restart: always
    environment:
      - APP_TYPE=scheduler
      - DATABASE_URL=postgresql+psycopg2://gc-xdefiant:3a56ba95118f2dda2de6da3d2da18e1a@database:5432/gc-xdefiant
    volumes:
      - data-xdefiant:/app
    depends_on:
      - database

  database:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=gc-xdefiant
      - POSTGRES_PASSWORD=3a56ba95118f2dda2de6da3d2da18e1a
      - POSTGRES_DB=gc-xdefiant
    volumes:
      - postgres-gc-xdefiant:/var/lib/postgresql/data


volumes:
    postgres-gc-xdefiant:
    data-xdefiant:
