services:
  cf_resolver:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    environment:
      LOG_LEVEL: info
    restart: unless-stopped

  database:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=gc-xdefiant
      - POSTGRES_PASSWORD=3a56ba95118f2dda2de6da3d2da18e1a
      - POSTGRES_DB=gc-xdefiant
    volumes:
      - postgres-gc-xdefiant:/var/lib/postgresql/data
    ports:
      - "567:5432"
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U gc-xdefiant"]
        interval: 10s
        timeout: 5s
        retries: 5

  discord-bot:
    build: .
    container_name: discord-bot
    restart: always
    environment:
      - APP_TYPE=bot
      - DATABASE_URL=postgresql+psycopg2://gc-xdefiant:3a56ba95118f2dda2de6da3d2da18e1a@database:5432/gc-xdefiant
      - CF_RESOLVER_URL=http://cf_resolver:8191/v1
    volumes:
      - data-xdefiant:/app
    depends_on:
      database:
        condition: service_healthy

  scheduler:
    build: .
    container_name: scheduler
    restart: always
    environment:
      - APP_TYPE=scheduler
      - DATABASE_URL=postgresql+psycopg2://gc-xdefiant:3a56ba95118f2dda2de6da3d2da18e1a@database:5432/gc-xdefiant
      - CF_RESOLVER_URL=http://cf_resolver:8191/v1
    volumes:
      - data-xdefiant:/app
    depends_on:
      database:
        condition: service_healthy

volumes:
    postgres-gc-xdefiant:
    data-xdefiant:
